// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatInputController from "./chat_input_controller.js"
application.register("chat-input", ChatInputController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LanguageSelectorController from "./language_selector_controller.js"
application.register("language-selector", LanguageSelectorController)
